version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: devtreedb
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: devtreedb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - devtree_network

volumes:
  mongodb_data:

networks:
  devtree_network:
    driver: bridge

