### Registro de usuario
POST http://localhost:3000/auth/register
Content-Type: application/json

{
   "handle": "Pepe Argento",
  "email": "pepe1@test.com",
  "password": "{{password}}",
  "name": "pepe"
}

